#! /bin/sh

case "`uname`" in
   Darwin*)
      GENERATORS="productbuild"
   ;;
   Linux*)
      GENERATORS="DEB:RPM"
   ;;
   Win*|Min*)
      GENERATORS="NSIS"
   ;;
   *)
      GENERATORS="TGZ"
   ;;
esac


GENERATORS="${1:-${GENERATORS}}"

if [ -z "${VERSION}" ]
then
   echo "Environment variable VERSION is not set" >&2
   exit 1
fi

echo "Generating package for ${VERSION}" >&2

if [ -d "package" ]
then
   rm -rf package || exit 1
fi


mkdir package || exit 1
cd package
cmake ${CMAKE_FLAGS} ..
make ${MAKE_FLAGS}

IFS=':'
for GENERATOR in ${GENERATORS}
do
   IFS=
   cpack ${CPACK_FLAGS} -G "${GENERATOR}" ..
done
IFS=
